import { Conversation } from "@/components/Inbox/ConversationList";

// Helper function to create timestamps
const getTimestamp = (hoursAgo: number) => {
  const date = new Date();
  date.setHours(date.getHours() - hoursAgo);
  return date.toISOString();
};

export const mockConversations: Conversation[] = [
  {
    id: "1",
    senderName: "Sarah Johnson",
    senderEmail: "sarah.j@techcorp.com",
    subject: "Interested in your product",
    preview: "Hi, I came across your product and I'm really interested in learning more about...",
    timestamp: getTimestamp(2),
    type: "email",
    status: "new",
    isRead: false,
    receivedAccount: {
      account_name: "Sales Account",
      account_email: "sales@converso.ai",
      account_type: "email",
    },
  },
  {
    id: "2",
    senderName: "Mike Chen",
    subject: "Following up on our conversation",
    preview: "Hey, thanks for connecting! I wanted to follow up on what we discussed...",
    timestamp: getTimestamp(5),
    type: "linkedin",
    status: "engaged",
    isRead: true,
    assignedTo: "John SDR",
    receivedAccount: {
      account_name: "John's LinkedIn",
      account_type: "linkedin",
    },
  },
  {
    id: "3",
    senderName: "Emily Rodriguez",
    senderEmail: "emily.r@startup.io",
    subject: "Partnership opportunity",
    preview: "I'm reaching out regarding a potential partnership between our companies...",
    timestamp: getTimestamp(24),
    type: "email",
    status: "qualified",
    isRead: true,
    assignedTo: "Jane SDR",
    receivedAccount: {
      account_name: "Partnerships",
      account_email: "partners@converso.ai",
      account_type: "email",
    },
  },
  {
    id: "4",
    senderName: "David Park",
    preview: "Your LinkedIn post about AI really resonated with me. Would love to chat...",
    timestamp: getTimestamp(48),
    type: "linkedin",
    status: "new",
    isRead: false,
    receivedAccount: {
      account_name: "Jane's LinkedIn",
      account_type: "linkedin",
    },
  },
  {
    id: "5",
    senderName: "Lisa Anderson",
    senderEmail: "l.anderson@bigcorp.com",
    subject: "Demo request",
    preview: "Our team would like to schedule a demo of your platform. Are you available...",
    timestamp: getTimestamp(72),
    type: "email",
    status: "converted",
    isRead: true,
    assignedTo: "John SDR",
    receivedAccount: {
      account_name: "Sales Account",
      account_email: "sales@converso.ai",
      account_type: "email",
    },
  },
  {
    id: "6",
    senderName: "Robert Taylor",
    senderEmail: "r.taylor@enterprise.com",
    subject: "Enterprise pricing inquiry",
    preview: "We're looking to roll out your solution to 500+ users. Can we discuss pricing...",
    timestamp: getTimestamp(96),
    type: "email",
    status: "qualified",
    isRead: true,
    assignedTo: "Jane SDR",
    receivedAccount: {
      account_name: "Sales Account",
      account_email: "sales@converso.ai",
      account_type: "email",
    },
  },
  {
    id: "7",
    senderName: "Amanda White",
    preview: "I saw your demo at the conference last week. Really impressive stuff!",
    timestamp: getTimestamp(168),
    type: "linkedin",
    status: "engaged",
    isRead: true,
    receivedAccount: {
      account_name: "John's LinkedIn",
      account_type: "linkedin",
    },
  },
  {
    id: "8",
    senderName: "Chris Martinez",
    senderEmail: "c.martinez@saascompany.io",
    subject: "Integration possibilities",
    preview: "We're exploring integration options with AI tools. Is your API documented...",
    timestamp: getTimestamp(168),
    type: "email",
    status: "new",
    isRead: false,
    receivedAccount: {
      account_name: "Partnerships",
      account_email: "partners@converso.ai",
      account_type: "email",
    },
  },
  {
    id: "9",
    senderName: "Jennifer Lee",
    senderEmail: "j.lee@techstartup.com",
    subject: "Question about features",
    preview: "Does your platform support multi-channel management? We need both email and LinkedIn...",
    timestamp: getTimestamp(3),
    type: "email",
    status: "new",
    isRead: false,
    assignedTo: "John SDR",
    receivedAccount: {
      account_name: "Sales Account",
      account_email: "sales@converso.ai",
      account_type: "email",
    },
  },
  {
    id: "10",
    senderName: "Tom Wilson",
    preview: "Your content on LinkedIn is great! We should connect and discuss how AI can help our team.",
    timestamp: getTimestamp(6),
    type: "linkedin",
    status: "engaged",
    isRead: true,
    assignedTo: "Jane SDR",
    receivedAccount: {
      account_name: "Jane's LinkedIn",
      account_type: "linkedin",
    },
  },
  {
    id: "11",
    senderName: "Karen Smith",
    senderEmail: "karen@mediumcorp.com",
    subject: "Ready to move forward",
    preview: "We've reviewed the proposal and are ready to move forward with implementation...",
    timestamp: getTimestamp(120),
    type: "email",
    status: "converted",
    isRead: true,
    assignedTo: "John SDR",
    receivedAccount: {
      account_name: "Sales Account",
      account_email: "sales@converso.ai",
      account_type: "email",
    },
  },
  {
    id: "12",
    senderName: "Alex Brown",
    preview: "Thanks for the info, but we decided to go with another solution.",
    timestamp: getTimestamp(168),
    type: "linkedin",
    status: "not_interested",
    isRead: true,
    assignedTo: "Mike SDR",
    receivedAccount: {
      account_name: "John's LinkedIn",
      account_type: "linkedin",
    },
  },
  {
    id: "13",
    senderName: "Patricia Davis",
    senderEmail: "p.davis@bigcompany.com",
    subject: "Budget approved",
    preview: "Great news! Our budget for Q2 has been approved. Let's schedule onboarding...",
    timestamp: getTimestamp(48),
    type: "email",
    status: "qualified",
    isRead: true,
    assignedTo: "Jane SDR",
    receivedAccount: {
      account_name: "Sales Account",
      account_email: "sales@converso.ai",
      account_type: "email",
    },
  },
  {
    id: "14",
    senderName: "James Miller",
    preview: "Appreciate the demo, but the pricing is too high for us right now.",
    timestamp: getTimestamp(72),
    type: "linkedin",
    status: "not_interested",
    isRead: true,
    assignedTo: "John SDR",
    receivedAccount: {
      account_name: "Jane's LinkedIn",
      account_type: "linkedin",
    },
  },
  {
    id: "15",
    senderName: "Monica Garcia",
    senderEmail: "m.garcia@startup.io",
    subject: "Following up on demo",
    preview: "The demo was fantastic! Our team has a few technical questions before we proceed...",
    timestamp: getTimestamp(12),
    type: "email",
    status: "engaged",
    isRead: true,
    assignedTo: "Jane SDR",
    receivedAccount: {
      account_name: "Sales Account",
      account_email: "sales@converso.ai",
      account_type: "email",
    },
  },
];

export interface MockMessage {
  id: string;
  senderName: string;
  content: string;
  timestamp: string;
  isFromLead: boolean;
}

export const mockMessagesByConversation: Record<string, MockMessage[]> = {
  "1": [
    {
      id: "1-1",
      senderName: "Sarah Johnson",
      content: "Hi, I came across your product and I'm really interested in learning more about how it can help our sales team. We currently have 15 SDRs managing around 300 leads per month, and response times are becoming an issue. Do you have time for a quick call this week?",
      timestamp: "2 hours ago",
      isFromLead: true,
    },
    {
      id: "1-2",
      senderName: "You",
      content: "Hi Sarah! Thanks for reaching out. I'd be happy to show you how Converso AI can help your team manage those leads more efficiently and improve response times. I have availability on Tuesday at 2pm or Thursday at 10am. Which works better for you?",
      timestamp: "1 hour ago",
      isFromLead: false,
    },
  ],
  "2": [
    {
      id: "2-1",
      senderName: "Mike Chen",
      content: "Hey, great to connect! I wanted to follow up on what we discussed at the conference last month. Your AI-powered inbox management solution sounds perfect for what we're trying to achieve.",
      timestamp: "5 hours ago",
      isFromLead: true,
    },
    {
      id: "2-2",
      senderName: "You",
      content: "Likewise Mike! Glad we got to chat at the event. I can share a short deck and a 15-min Loom video that shows exactly how we help teams like yours. Would that be helpful?",
      timestamp: "4 hours ago",
      isFromLead: false,
    },
    {
      id: "2-3",
      senderName: "Mike Chen",
      content: "That would be perfect. Also, do you have any case studies from companies in the SaaS space?",
      timestamp: "3 hours ago",
      isFromLead: true,
    },
  ],
  "3": [
    {
      id: "3-1",
      senderName: "Emily Rodriguez",
      content: "Hi! I'm reaching out regarding a potential partnership between our companies. We're exploring tools that help SDR teams scale their outreach, and Converso AI looks like it could be a great fit for our customer base.",
      timestamp: "1 day ago",
      isFromLead: true,
    },
    {
      id: "3-2",
      senderName: "You",
      content: "Thanks Emily! I think Converso AI could be a good fit for a partnership. Here's how our current partners typically integrate our solution... [continues with details about partnership models]",
      timestamp: "22 hours ago",
      isFromLead: false,
    },
    {
      id: "3-3",
      senderName: "Emily Rodriguez",
      content: "This sounds promising. Could we set up a call with our partnerships team next week?",
      timestamp: "20 hours ago",
      isFromLead: true,
    },
  ],
  "4": [
    {
      id: "4-1",
      senderName: "David Park",
      content: "Your LinkedIn post about AI in sales development really resonated with me. We're currently evaluating solutions to help our outbound strategy. Would love to chat about what you're seeing across SDR teams.",
      timestamp: "2 days ago",
      isFromLead: true,
    },
    {
      id: "4-2",
      senderName: "You",
      content: "Appreciate that David! Happy to share what we're seeing. Most teams we work with are struggling with similar challenges around lead response times and inbox management. Are you free for a brief call this week?",
      timestamp: "1 day ago",
      isFromLead: false,
    },
  ],
  "5": [
    {
      id: "5-1",
      senderName: "Lisa Anderson",
      content: "Hi there, our team would like to schedule a demo of your platform. We're particularly interested in the AI-powered lead routing features. Are you available next week for a 30-minute demo?",
      timestamp: "3 days ago",
      isFromLead: true,
    },
    {
      id: "5-2",
      senderName: "You",
      content: "Hi Lisa, that's great to hear! I'll send over a few time slots and a short agenda for the demo. We can definitely dive deep into the lead routing capabilities.",
      timestamp: "2 days ago",
      isFromLead: false,
    },
    {
      id: "5-3",
      senderName: "Lisa Anderson",
      content: "Perfect! Wednesday at 2pm works for our team. Looking forward to it.",
      timestamp: "2 days ago",
      isFromLead: true,
    },
    {
      id: "5-4",
      senderName: "You",
      content: "Wednesday at 2pm is confirmed. I'll send a calendar invite with the meeting link shortly. See you then!",
      timestamp: "2 days ago",
      isFromLead: false,
    },
  ],
  "6": [
    {
      id: "6-1",
      senderName: "Robert Taylor",
      content: "We're looking to roll out your solution to 500+ users across our sales org. Can we discuss enterprise pricing and implementation timelines? This would be a significant deployment for us.",
      timestamp: "4 days ago",
      isFromLead: true,
    },
    {
      id: "6-2",
      senderName: "You",
      content: "Hi Robert, thanks for reaching out! I'd love to discuss an enterprise deployment. For organizations of your size, we offer dedicated onboarding, custom integrations, and priority support. Let me connect you with our enterprise team.",
      timestamp: "3 days ago",
      isFromLead: false,
    },
  ],
  "7": [
    {
      id: "7-1",
      senderName: "Amanda White",
      content: "I saw your demo at the SaaS Connect conference last week. Really impressive stuff! Our team is currently evaluating inbox management solutions. Can we schedule a follow-up call?",
      timestamp: "1 week ago",
      isFromLead: true,
    },
    {
      id: "7-2",
      senderName: "You",
      content: "Hi Amanda! Great meeting you at SaaS Connect. I'm glad you found the demo valuable. I'd be happy to do a personalized walkthrough for your team. How does next Tuesday look?",
      timestamp: "6 days ago",
      isFromLead: false,
    },
  ],
  "8": [
    {
      id: "8-1",
      senderName: "Chris Martinez",
      content: "We're exploring integration options with AI-powered sales tools. Is your API well-documented? We'd need to connect it with our existing CRM and communication platforms.",
      timestamp: "1 week ago",
      isFromLead: true,
    },
  ],
};

// Default export for backward compatibility
export const mockMessages = mockMessagesByConversation["1"];

export const mockTeamMembers = [
  {
    id: "1",
    name: "John SDR",
    email: "john@company.com",
    role: "sdr" as const,
    assignedInboxes: 3,
    activeLeads: 12,
    conversionRate: 24,
    isActive: true,
    emailsAllocated: 45,
    dmsAllocated: 18,
    pendingResponse: 8,
    engaged: 34,
  },
  {
    id: "2",
    name: "Jane SDR",
    email: "jane@company.com",
    role: "sdr" as const,
    assignedInboxes: 2,
    activeLeads: 8,
    conversionRate: 31,
    isActive: true,
    emailsAllocated: 38,
    dmsAllocated: 22,
    pendingResponse: 5,
    engaged: 28,
  },
  {
    id: "3",
    name: "Mike SDR",
    email: "mike@company.com",
    role: "sdr" as const,
    assignedInboxes: 2,
    activeLeads: 15,
    conversionRate: 18,
    isActive: false,
    emailsAllocated: 52,
    dmsAllocated: 15,
    pendingResponse: 10,
    engaged: 22,
  },
];

export const mockAnalytics = {
  emailsReceived: [
    { date: "Mon", count: 23 },
    { date: "Tue", count: 31 },
    { date: "Wed", count: 28 },
    { date: "Thu", count: 35 },
    { date: "Fri", count: 29 },
    { date: "Sat", count: 12 },
    { date: "Sun", count: 8 },
  ],
  conversionFunnel: [
    { stage: "New Leads", count: 150 },
    { stage: "Engaged", count: 89 },
    { stage: "Qualified", count: 45 },
    { stage: "Converted", count: 18 },
  ],
  sdrPerformance: [
    { name: "John", engagement: 85, conversion: 24, response: 92 },
    { name: "Jane", engagement: 92, conversion: 31, response: 88 },
    { name: "Mike", engagement: 78, conversion: 18, response: 95 },
  ],
  trendData: [
    { date: "Week 1", leads: 45, conversions: 12, engagement: 78, responseTime: 2.5 },
    { date: "Week 2", leads: 52, conversions: 15, engagement: 82, responseTime: 2.2 },
    { date: "Week 3", leads: 48, conversions: 14, engagement: 85, responseTime: 2.0 },
    { date: "Week 4", leads: 61, conversions: 18, engagement: 88, responseTime: 1.8 },
    { date: "Week 5", leads: 58, conversions: 16, engagement: 86, responseTime: 1.9 },
    { date: "Week 6", leads: 67, conversions: 21, engagement: 90, responseTime: 1.7 },
    { date: "Week 7", leads: 72, conversions: 23, engagement: 92, responseTime: 1.5 },
    { date: "Week 8", leads: 69, conversions: 22, engagement: 91, responseTime: 1.6 },
    { date: "Week 9", leads: 78, conversions: 26, engagement: 94, responseTime: 1.4 },
    { date: "Week 10", leads: 82, conversions: 28, engagement: 95, responseTime: 1.3 },
    { date: "Week 11", leads: 76, conversions: 25, engagement: 93, responseTime: 1.5 },
    { date: "Week 12", leads: 85, conversions: 30, engagement: 96, responseTime: 1.2 },
  ],
};